name: dominick
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  unicons: ^2.1.1
  # scrollable_positioned_list: ^0.3.8
  device_preview: ^1.1.0
  # animated_background: ^2.0.0
  # bamboo: ^1.0.3
  flutter_svg: ^2.0.10+1
  # expansion_tile_card: ^3.0.0
  # assets_audio_player: ^3.1.1
  # assets_audio_player_web: ^3.1.1
  scroll_vanisher: ^1.0.3
  # overlapped_carousel: ^1.0.2
  # flutter_card_swiper: ^7.0.0
  flutter_carousel_widget: ^2.2.0
  url_launcher: ^6.2.6
  # meta_seo: ^3.0.9
  percent_indicator: ^4.2.3
  responsive_grid: ^2.4.4
  # theme_provider: ^0.6.0
  # flutter_speed_dial: ^7.0.0

# dependency_overrides:
#   web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/logo/
    - assets/icon/team.svg
    - assets/icon/project.svg
    - assets/icon/cup.svg
    - assets/icon/calendar.svg
    - assets/icon/mouse_icon.svg
    - assets/logo/ibonia.png
    - assets/logo/areaTech.png
    - assets/logo/myagency.png
    - assets/logo/google.png
    - assets/logo/esti.png
    - assets/logo/mybn.png
    - assets/logo/mvola.png
    - assets/logo/zahageek.png
    - assets/logo/iteams.png
    - assets/images/cekah.png
    - assets/images/cher_project.webp
    - assets/images/designer_project.webp
    - assets/images/dev_project.webp
    - assets/images/dekoa.webp
    - assets/images/portfolio.webp
    - assets/images/mozika.webp
    - assets/images/rakitra.webp
    - assets/images/gfs.webp
    - assets/images/buildeo.webp
    - assets/images/avg.webp
    - assets/images/croquis_cover.webp
    - assets/icon/team.svg
    - assets/icon/project.svg
    - assets/icon/cup.svg
    - assets/icon/calendar.svg
    - assets/icon/mouse_icon.svg


  fonts:
    - family: Aura
      fonts:
        - asset: assets/fonts/at-aura.ttf
    - family: Mortend
      fonts:
        - asset: assets/fonts/mortend/mortend_bold.otf
        - asset: assets/fonts/mortend/mortend_bold.ttf
    - family: FloPro
      fonts:
        - asset: assets/fonts/florida_project/FloProject_phase_one.otf
        - asset: assets/fonts/florida_project/FloProject_phase_one.ttf
        - asset: assets/fonts/florida_project/FloProject_phase_two.otf
        - asset: assets/fonts/florida_project/FloProject_phase_two.ttf

